name: Bandit Security Check

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Adjust the Python version as needed

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r .
