name: Run Bandit on Modified Python Files

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get the list of modified Python files
      id: get_pr_files
      run: |
        echo "Fetching modified Python files..."
        python get_modified_files.py
      shell: bash

    - name: Install Bandit
      run: |
        echo "Installing Bandit..."
        pip install bandit
      shell: bash

    - name: Run Bandit on modified Python files
      if: steps.get_pr_files.outputs.files != ''
      run: |
        echo "Running Bandit on modified Python files..."
        while IFS= read -r file; do
          bandit -r -ll -ii "$file"
        done < modified_files.txt
      shell: bash


