name: Check Checklist

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Checklist Items
        run: |
          python checklist_checker.py ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
