name: Check Version Update

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if _version.py is updated
        run: |
          CHANGED_FILES=$(jq -r '.pull_request.changed_files' "$GITHUB_EVENT_PATH")
          if ! echo "$CHANGED_FILES" | grep -q 'test_utils/_version.py'; then
            echo "Error: _version.py file must be updated in this pull request."
            ex
