name: Tag on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Extract major version
        id: extract_version
        run: |
          VERSION=$(grep -oP '(?<=__version__ = ")[^"]*' test_utils/_version.py)
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          echo "::set-output name=tag_name::v$MAJOR_VERSION"

      - name: Debug - Print Tag Name
        run: echo "Tag name is ${{ steps.extract_version.outputs.tag_name }}"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check if Tag Exists
        env:
          TAG_NAME: ${{ steps.extract_version.outputs.tag_name }}
        run: |
          if git rev-parse $TAG_NAME >/dev/null 2>&1; then
            echo "Tag $TAG_NAME exists"
          else
            echo "Tag $TAG_NAME does not exist"
          fi

      - name: Delete existing tag if it exists
        env:
          TAG_NAME: ${{ steps.extract_version.outputs.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git rev-parse $TAG_NAME >/dev/null 2>&1; then
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} :refs/tags/$TAG_NAME
          fi

      - name: Create and Push Tag
        env:
          TAG_NAME: ${{ steps.extract_version.outputs.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $TAG_NAME
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME