name: Tag on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.extract_version.outputs.tag_name }}" >/dev/null 2>&1; then
            echo "Tag already exists"
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag does not exist"
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        env:
          TAG_NAME: ${{ steps.extract_version.outputs.tag_name }}
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
